//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cafemax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticket_usu
    {
        public int id_t { get; set; }
        public string fecha_t { get; set; }
        public string venta_t { get; set; }
        public string usuario_t { get; set; }
        public string codigo_t { get; set; }
    }
}
