//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriamx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id_prod { get; set; }
        public int tipo_prod { get; set; }
        public int invetario_prod { get; set; }
        public double precio_prod { get; set; }
        public string nombre_prod { get; set; }
        public string img_prod { get; set; }
    }
}
