//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafeteriamx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos_ofertas
    {
        public int id_ofertas { get; set; }
        public int invetario_ofertas { get; set; }
        public double precio_ofertas { get; set; }
        public string nombre_ofertas { get; set; }
        public string img_ofertas { get; set; }
        public string descripcion_ofertas { get; set; }
    }
}
